### PR TITLE
Fix #2381: Allow the Ledger to return an empty validator set

### LINKED ISSUE #2381: Ensure `/validators` endpoint returns `null` when the requested height is above its known one
Otherwise we get the lovely:
```JSON
{"statusMessage":"An Exception occured","statusDebugMessage":"agora.common.Ensure.FormattedException@source/agora/consensus/Ledger.d(248): Ledger.getValidators didn't find any validator at height 9999999\n----------------\nsource/agora/common/Ensure.d:102 @safe void agora.common.Ensure.ensure!(const(agora.common.Types.Height)).ensure(bool, immutable(char)[], lazy const(agora.common.Types.Height), immutable(char)[], int) [0x562b673684f0]\nsource/agora/consensus/Ledger.d:245 scope @safe agora.consensus.data.ValidatorInfo.ValidatorInfo[] agora.consensus.Ledger.Ledger.getValidators(in agora.common.Types.Height) [0x562b672dfb30]\nsource/agora/node/FullNode.d:1288 @safe agora.consensus.data.ValidatorInfo.ValidatorInfo[] agora.node.FullNode.FullNode.getValidators(ulong) [0x562b672e4300]\nsubmodules/vibe.d/web/vibe/web/rest.d:1463 @safe void vibe.web.rest.jsonMethodHandler!(agora.api.FullNode.API.getValidators(ulong), 19uL, agora.api.Validator.API).jsonMethodHandler(agora.api.Validator.API, ref vibe.web.internal.rest.common.RestInterface!(agora.api.Validator.API).RestInterface).handler(vibe.http.server.HTTPServerRequest, vibe.http.server.HTTPServerResponse) [0x562b674fd580]\nsubmodules/vibe.d/http/vibe/http/router.d:211 @safe bool vibe.http.router.URLRouter.handleRequest(vibe.http.server.HTTPServerRequest, vibe.http.server.HTTPServerResponse).__lambda6!(ulong, immutable(char)[][]).__lambda6(ulong, scope immutable(char)[][]) [0x562b6787e910]\nsubmodules/vibe.d/http/vibe/http/router.d:718 const @safe bool vibe.http.router.MatchTree!(vibe.http.router.Route).MatchTree.doMatch(immutable(char)[], scope bool delegate(ulong, scope immutable(char)[][]) @safe) [0x562b678820e0]\nsubmodules/vibe.d/http/vibe/http/router.d:662 @safe bool vibe.http.router.MatchTree!(vibe.http.router.Route).MatchTree.match(immutable(char)[], scope bool delegate(ulong, scope immutable(char)[][]) @safe) [0x562b6787e8b0]\nsubmodules/vibe.d/http/vibe/http/router.d:194 @safe void vibe.http.router.URLRouter.handleRequest(vibe.http.server.HTTPServerRequest, vibe.http.server.HTTPServerResponse) [0x562b6787e540]\nsubmodules/vibe.d/http/vibe/http/server.d:2120 @safe bool vibe.http.server.handleRequest(vibe.internal.interfaceproxy.InterfaceProxy!(vibe.core.stream.Stream).InterfaceProxy, vibe.core.net.TCPConnection, vibe.http.server.HTTPServerContext, ref vibe.http.server.HTTPServerSettings, ref bool, scope stdx.allocator.IAllocator) [0x562b67887f90]\nsubmodules/vibe.d/http/vibe/http/server.d:245 @trusted void vibe.http.server.handleHTTPConnection(vibe.core.net.TCPConnection, vibe.http.server.HTTPServerContext).__lambda15() [0x562b67887e10]\nsubmodules/vibe.d/http/vibe/http/server.d:196 @safe void vibe.http.server.handleHTTPConnection(vibe.core.net.TCPConnection, vibe.http.server.HTTPServerContext) [0x562b67887220]\nsubmodules/vibe.d/http/vibe/http/server.d:2061 nothrow @safe void vibe.http.server.listenHTTPPlain(vibe.http.server.HTTPServerSettings, void delegate(vibe.http.server.HTTPServerRequest, vibe.http.server.HTTPServerResponse) @safe).doListen(vibe.http.server.HTTPServerContext, bool, bool, bool, bool).__lambda7(vibe.core.net.TCPConnection) [0x562b67894ff0]\nsubmodules/vibe-core/source/vibe/core/task.d:708 nothrow void vibe.core.task.TaskFuncInfo.set!(void delegate(vibe.core.net.TCPConnection) nothrow @safe, vibe.core.net.TCPConnection).set(ref void delegate(vibe.core.net.TCPConnection) nothrow @safe, ref vibe.core.net.TCPConnection).callDelegate(ref vibe.core.task.TaskFuncInfo) [0x562b67a7dc60]\nsubmodules/vibe-core/source/vibe/core/task.d:737 void vibe.core.task.TaskFuncInfo.call() [0x562b67a77f60]\nsubmodules/vibe-core/source/vibe/core/task.d:403 nothrow void vibe.core.task.TaskFiber.run() [0x562b67a77460]\n??:? fiber_entryPoint [0x7f669831e0a0]"}
```

### PR DESCRIPTION
**Pull request by Geod24**
In some scenarios, one might want to look up validators in the future.
In that case, they would call GET /validators with an arbitrarily high
height value, which might cause an exception internally.

### CODE REVIEW

**Review by hewison-chris — APPROVED** [review]
LGTM

File: source/agora/consensus/Ledger.d [hunk 1]
```diff
@@ -233,19 +233,23 @@ public class Ledger
           height = Height at which to query the validator set.
                    Accurate results are only guaranteed for
                    `height <= this.getBlockHeight() + 1`.
+          empty = Whether to allow an empty returrn value.
```
Comment (kchulj) [inline source/agora/consensus/Ledger.d]:
```suggestion
          empty = Whether to allow an empty return value.
```

Comment (linked0) [inline source/agora/consensus/Ledger.d]:
```suggestion
          empty = Whether to allow an empty return value.
```

**Review by linked0 — APPROVED** [review]
LGTM, one typo.

**Review by kchulj — APPROVED** [review]
LGTM

**Comment by Geod24** [comment]
Good eyes :)
