### PR TITLE
Make isQuorumSetSane() more informative

### LINKED ISSUE #515: `isQuorumSetSane` is not informative
Currently, when this check fails, there is no mention on *why* (which check) it fails, nor what data made it fail.

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
If this looks good to you, I will also submit a PR upstream.

However in upstream they already use a different set of rules for `isQuorumSetSane`, so we would have to update our bindings to the latest version first. And that's not trivial as of now.

Part of #515

### CODE REVIEW

**Comment by Geod24** [comment]
Probably need to use `std::string` to satisfy upstream.

**Comment by AndrejMitrovic** [comment]
> Probably need to use std::string to satisfy upstream.

That would upset downstream. :>

File: source/scpp/src/scp/QuorumSetUtils.cpp [hunk 1]
```diff
@@ -33,24 +34,50 @@ class QuorumSetSanityChecker
...
     : mExtraChecks{extraChecks}
 {
-    mIsSane = checkSanity(qSet, 0) && mCount >= 1 && mCount <= 1000;
+    mIsSane = checkSanity(qSet, 0, reason);
+
+    if (mCount < 1 || mCount > 1000)
+    {
+        if (reason != nullptr)
+        {
+            const char* msg = "Number of validator nodes exceeds the limit [1..1000]";
```
Comment (Geod24) [inline source/scpp/src/scp/QuorumSetUtils.cpp]: Technically it's out of bounds, as it can be `0`.
You could also split it up into "Quorum set has no validator" and "Quorum set has over 1000 validators".

File: source/scpp/src/scp/QuorumSetUtils.cpp [hunk 2]
```diff
@@ -33,24 +34,50 @@ class QuorumSetSanityChecker
...
 };
 
 QuorumSetSanityChecker::QuorumSetSanityChecker(SCPQuorumSet const& qSet,
-                                               bool extraChecks)
+                                               bool extraChecks,
+                                               const char** reason)
     : mExtraChecks{extraChecks}
 {
-    mIsSane = checkSanity(qSet, 0) && mCount >= 1 && mCount <= 1000;
+    mIsSane = checkSanity(qSet, 0, reason);
```
Comment (Geod24) [inline source/scpp/src/scp/QuorumSetUtils.cpp]: You can simplify the code by making the `reason` optional on the API, but required in the functions (IOW provides a dummy variable if `reason` is null so you avoid bounds check).

**Comment by AndrejMitrovic** [comment]
Can we already use `std::string` in D code? I see there's some support code in https://github.com/dlang/druntime/blob/master/src/core/stdcpp/string.d

**Comment by Geod24** [comment]
I think we can, as long as we don't copy it and just read it.

**Comment by AndrejMitrovic** [comment]
Fixed to avoid bounds / null checking. I'm using `std::string` in another branch (https://github.com/AndrejMitrovic/agora/tree/quorum-is-sane%2Bstd-string), but it fails with:

```
libstdc++ std::__cxx11::basic_string is not yet supported; the struct contains an interior pointer which breaks D move semantics!
```

File: source/scpp/src/scp/QuorumSetUtils.cpp [hunk 3]
```diff
@@ -33,24 +34,50 @@ class QuorumSetSanityChecker
...
 {
-    mIsSane = checkSanity(qSet, 0) && mCount >= 1 && mCount <= 1000;
+    const char* msg;
+    if (reason == nullptr)
+        reason = &msg;  // avoid null checks in checkSanity()
+
+    mIsSane = checkSanity(qSet, 0, reason);
+    if (mCount < 1)
+    {
+        const char* msg = "Number of validator nodes is zero";
```
Comment (Geod24) [inline source/scpp/src/scp/QuorumSetUtils.cpp]: Am I missing something w.r.t. the `const char* msg = ...; *reason = msg` pattern ? Wouldn't `*reason = ...` be more straightforward ?
Also assert that `reason` and `mIsSane` are consistent at the end of this constructor.

**Comment by Geod24** [comment]
> but it fails with:

Sad!

File: source/scpp/src/scp/BallotProtocol.cpp [hunk 4]
```diff
@@ -247,10 +247,17 @@ bool
 BallotProtocol::isStatementSane(SCPStatement const& st, bool self)
 {
     auto qSet = mSlot.getQuorumSetFromStatement(st);
-    bool res = qSet != nullptr && isQuorumSetSane(*qSet, false);
+    const char* reason;
```
Comment (AndrejMitrovic) [inline source/scpp/src/scp/BallotProtocol.cpp]: bad bad bad! no `T.init` in C++.

**Comment by AndrejMitrovic** [comment]
Updated.

File: source/scpp/src/scp/QuorumSetUtils.cpp [hunk 5]
```diff
@@ -33,24 +34,49 @@ class QuorumSetSanityChecker
...
+        mIsSane = false;
+    }
+    else if (mCount > 1000)
+    {
+        *reason = "Number of validator nodes exceeds the limit of 1000";
+        mIsSane = false;
+    }
+
+    // only one of the two may be true
+    assert(mIsSane ^ (*reason != nullptr));
```
Comment (Geod24) [inline source/scpp/src/scp/QuorumSetUtils.cpp:62]: Attaboy

**Review by Geod24 — APPROVED** [review]
