### PR TITLE
Registry: Fix putting multiple A records into single RR

### LINKED ISSUE #2993: A records are combined within RDATA of same RR
RFC 1035 [states](https://datatracker.ietf.org/doc/html/rfc1035#section-3.4.1) that each should be in its own ResourceRecord (RR).

### PR DESCRIPTION
**Pull request by mkykadir**
Each A record should be returned in its own RR

Fixes #2993

### CODE REVIEW

File: source/agora/node/Registry.d [hunk 1]
```diff
@@ -693,37 +693,36 @@ private struct TypedPayload
...
-                (addr) {
-                    scope in_addr = new InternetAddress(addr,
-                                        InternetAddress.PORT_ANY);
-
-                    // TODO SRV is needed to keep intact
-                    return Address("http://" ~ in_addr.toAddrString());
-                }
-            ).array;
+            scope in_addr = new InternetAddress(rr.rdata.a,
+                                InternetAddress.PORT_ANY);
```
Comment (Geod24) [inline source/agora/node/Registry.d]: `struct IPv4` can also be used here 👀

File: source/agora/node/Registry.d [hunk 2]
```diff
@@ -693,37 +693,36 @@ private struct TypedPayload
...
+
+            // TODO SRV is needed to keep intact
+            reg_payload.addresses ~= Address("http://" ~ in_addr.toAddrString());
```
Comment (Geod24) [inline source/agora/node/Registry.d]: In particular `Address(format("http://%s", IPv4(rr.rdata.a)))`.

**Review by Geod24 — APPROVED** [review]
나이스
