### PR TITLE
RPC: RPCConnections can now handle requests in both directions

### LINKED ISSUE #2534: Transactions do not propagate to an outsider node
After the commit [9dd1e4ffc](https://github.com/bosagora/agora/commit/9dd1e4ffcdc90844e5d554e970d509f0448876fb), the following code fails with the log like,
"Client #6 did not receive tx in expected time for height 19".

```
    TestConf conf = {
        outsider_validators : 1,
    };

    auto network = makeTestNetwork!TestAPIManager(conf);
    network.start();
    scope(exit) network.shutdown();
    scope(failure) network.printLogs();
    network.waitForDiscovery();

    network.generateBlocks(Height(GenesisValidatorCycle - 2));
    network.generateBlocks(iota(GenesisValidators + 1), Height(GenesisValidatorCycle - 1));
```

The error log
```
core.exception.AssertError@source/agora/test/Base.d(1070): Check condition failed after timeout of 4 secs and 40 attempts: [source/agora/test/ClearFilter.d:42] Client #6 did not receive tx in expected time for height 19
----------------
??:? void agora.utils.Utility.retryFor!(core.exception.AssertError).retryFor(lazy bool, core.time.Duration, lazy immutable(char)[], immutable(char)[], ulong) [0x10b0d22ee]
??:? void agora.test.Base.TestAPIManager.addBlock!(std.range.iota!(ulong, ulong).iota(ulong, ulong).Result).addBlock(std.range.iota!(ulong, ulong).iota(ulong, ulong).Result, bool, immutable(char)[], int).__lambda13!(ulong).__lambda13(ulong) [0x10b6e91b3]
??:? std.typecons.Flag!("each").Flag std.algorithm.iteration.each!(agora.test.Base.TestAPIManager.addBlock!(std.range.iota!(ulong, ulong).iota(ulong, ulong).Result).addBlock(std.range.iota!(ulong, ulong).iota(ulong, ulong).Result, bool, immutable(char)[], int).__lambda13).each!(std.range.iota!(ulong, ulong).iota(ulong, ulong).Result).each(std.range.iota!(ulong, ulong).iota(ulong, ulong).Result) [0x10b6e8e07]
??:? void agora.test.Base.TestAPIManager.addBlock!(std.range.iota!(ulong, ulong).iota(ulong, ulong).Result).addBlock(std.range.iota!(ulong, ulong).iota(ulong, ulong).Result, bool, immutable(char)[], int) [0x10b6e8afd]
??:? void agora.test.Base.TestAPIManager.generateBlocks!(std.range.iota!(ulong, ulong).iota(ulong, ulong).Result).generateBlocks(std.range.iota!(ulong, ulong).iota(ulong, ulong).Result, agora.common.Types.Height, bool, immutable(char)[], int).__lambda9!(ulong).__lambda9(ulong) [0x10b6e88d1]
```

### PR DESCRIPTION
**Pull request by omerfirmak**
No concurrent request in the same direction.

### CODE REVIEW

**Comment by omerfirmak** [comment]
@Geod24 , I can't push to our `vibe-core` fork.

**Comment by Geod24** [comment]
@omerfirmak : Fixed

File: source/agora/network/RPC.d [hunk 1]
```diff
@@ -298,6 +289,12 @@ private class RPCConnection
 
     ///
     alias conn this;
+
+    ///
+    this (TCPConnection conn) @safe
```
Comment (Geod24) [inline source/agora/network/RPC.d]: Attributes. Especially `nothrow` because the compiler generates much more efficient code for `nothrow` ctors.

File: source/agora/network/Manager.d [hunk 2]
```diff
@@ -1101,7 +1105,7 @@ public class NetworkManager
 
     ***************************************************************************/
 
-    protected API getClient (Address address, Duration timeout)
+    protected agora.api.Validator.API getClient (Address address, Duration timeout)
```
Comment (Geod24) [inline source/agora/network/Manager.d:1153]: Why does this return a `Validator` API ? What happens for full nodes ?

**Review by Geod24 — COMMENTED** [review]
I see the main problem is that it creates a dependency between the `NetworkManager` and the calling node. Will take a deeper look tomorrow after the release.

File: source/agora/network/Manager.d (hunk 2 above)
Comment (omerfirmak) [reply source/agora/network/Manager.d:1153]: `API` was always `Validator.API` , we just have to specify it explicitly now that I have also imported `FullNode.API`.

> What happens for full nodes ?

Nothing, we just don't call `Validator` only endpoints on them.

**Comment by omerfirmak** [comment]
> I see the main problem is that it creates a dependency between the NetworkManager and the calling node. Will take a deeper look tomorrow after the release.

Yeah, I don't like that either. I'll update it if I find a cleaner solution.

**Comment by omerfirmak** [comment]
Updated with discovery thru incoming RPC conns. Integration is happy.

**Comment by Geod24** [comment]
> RPC: Remove RPC client lookup table

Why ?

**Comment by Geod24** [comment]
Please upstream the vibe-core fixes.

**Comment by omerfirmak** [comment]
> 
> 
> > RPC: Remove RPC client lookup table
> 
> Why ?

Dropped it.

> Please upstream the vibe-core fixes.

Will do

File: source/agora/network/Manager.d [hunk 3]
```diff
@@ -129,6 +133,19 @@ public class NetworkManager
             @safe pure nothrow @nogc
         {
             this.address = address;
+            this.api = null;
+            this.onHandshakeComplete = onHandshakeComplete;
+            this.onFailedRequest = onFailedRequest;
```
Comment (Geod24) [inline source/agora/network/Manager.d]:
```suggestion
            this(null, address, onHandshakeComplete, onFailedRequest);
```

File: source/agora/network/Manager.d [hunk 4]
```diff
@@ -129,6 +133,19 @@ public class NetworkManager
...
+        }
+
+        public this (agora.api.Validator.API api,
+            void delegate (scope ref NodeConnInfo node) onHandshakeComplete,
+            bool delegate (in Address address) onFailedRequest,
+            Address address = Address.init)
```
Comment (Geod24) [inline source/agora/network/Manager.d]: Do we need a default value ?
If not, keep the parameters in the same order (e.g. `address` after `api`).

**Review by Geod24 — APPROVED** [review]
One last thing

**Comment by Geod24** [comment]
Rebased it and addressed my comments.

**Comment by omerfirmak** [comment]
So this is back

```
[source/agora/test/Base.d:1339] Assertion thrown during test: Trying to access node at address 'Validator-1.boa1xzval2a3cdxv28n6slr62wlczslk3juvk7cu05qt3z55ty2rlfqfc6egsh2.localrest' from 'Validator-1.boa1xzval2a3cdxv28n6slr62wlczslk3juvk7cu05qt3z55ty2rlfqfc6egsh2.localrest' without first creating it
source/agora/test/Base.d:1339 agora.test.Base.TestAPI agora.test.Base.TestNetworkManager.getClient(immutable(char)[], core.time.Duration) [0x103c58d9f]
source/agora/network/Manager.d:186 void agora.network.Manager.NetworkManager.ConnectionTask.connect_canthrow() [0x103d97471]
source/agora/network/Manager.d:177 nothrow void agora.network.Manager.NetworkManager.ConnectionTask.connect() [0x103d9735b]
core/thread/context.d:46 void core.thread.context.Callable.opCall() [0x104a2bb9c]
core/thread/fiber.d:1141 void core.thread.fiber.Fiber.run() [0x104a2bd28]
core/thread/fiber.d:198 fiber_entryPoint [0x104a2bc65]
#### FATAL ERROR: Trying to access node at address 'Validator-1.boa1xzval2a3cdxv28n6slr62wlczslk3juvk7cu05qt3z55ty2rlfqfc6egsh2.localrest' from 'Validator-1.boa1xzval2a3cdxv28n6slr62wlczslk3juvk7cu05qt3z55ty2rlfqfc6egsh2.localrest' without first creating it
This node was started at source/agora/test/BlockRewards.d:45
This most likely means that the node crashed due to an uncaught exception
If not, please file a bug at https://github.com/Geod24/localrest/
Full error: core.exception.AssertError@source/agora/test/Base.d(1339): Trying to access node at address 'Validator-1.boa1xzval2a3cdxv28n6slr62wlczslk3juvk7cu05qt3z55ty2rlfqfc6egsh2.localrest' from 'Validator-1.boa1xzval2a3cdxv28n6slr62wlczslk3juvk7cu05qt3z55ty2rlfqfc6egsh2.localrest' without first creating it
```

**Comment by Geod24** [comment]
Yeah, but the worrying part is integration: Maybe my rebase was incorrect, as it seems to always re-establish connections.

**Comment by Geod24** [comment]
Also, it's a node trying to connect to itself. They should ban themselves. I'll take a look.

**Comment by omerfirmak** [comment]
> Yeah, but the worrying part is integration: Maybe my rebase was incorrect, as it seems to always re-establish connections.

That wasnt the case, I will take a look.

**Comment by omerfirmak** [comment]
Ok, I see what is happening. Incoming connections from FullNodes cannot be merged as they can not be identified by a key. So every time a FullNode initiates a connections, that is registered as a different peer. Which easily maxes the listener limit of a node.

**Comment by omerfirmak** [comment]
Also, now that we have both TCP and HTTP endpoints, they both count as a separate peer and take up a peer slot.

**Comment by Geod24** [comment]
Should / can we prioritize the tcp connection in that situation ?

**Comment by Geod24** [comment]
> Ok, I see what is happening. Incoming connections from FullNodes cannot be merged as they can not be identified by a key. So every time a FullNode initiates a connections, that is registered as a different peer. Which easily maxes the listener limit of a node.

Why does it keeps on initiating connections tho ?

**Review by Geod24 — APPROVED** [review]
