### PR TITLE
Make a node register as a listener with a valid address

### LINKED ISSUE #1051: Integration tests is sending requests to `0.0.0.0`
Just do a `docker-compose up` and see the logs:
```
node-3_1  | 2020-07-22 08:03:04,541 Trace [agora.network.NetworkClient] - Request 'getPublicKey' to http://0.0.0.0:3826 failed: Failed to connect to 0.0.0.0:3826: refused
node-3_1  | 2020-07-22 08:03:04,541 Trace [agora.network.NetworkClient] - Request 'getPublicKey' to http://0.0.0.0:2826 failed: Failed to connect to 0.0.0.0:2826: refused
node-3_1  | 2020-07-22 08:03:06,43 Trace [agora.network.NetworkClient] - Request 'getPublicKey' to http://0.0.0.0:4826 failed: Failed to connect to 0.0.0.0:4826: refused
node-3_1  | 2020-07-22 08:03:06,43 Trace [agora.network.NetworkClient] - Request 'getPublicKey' to http://0.0.0.0:3826 failed: Failed to connect to 0.0.0.0:3826: refused
node-3_1  | 2020-07-22 08:03:06,44 Trace [agora.network.NetworkClient] - Request 'getPublicKey' to http://0.0.0.0:2826 failed: Failed to connect to 0.0.0.0:2826: refused
```

I don't see why we would ever send a message to 0.0.0.0 ?

### PR DESCRIPTION
**Pull request by linked0**
This is the first PR for the #1051 issue and does not contain code making sure we keep the connection alive yet, which will be submitted with another PR. With the code @AndrejMitrovic suggested, I registered a path manually in vibe.d for registering a listener address.

With the talk with @Geod24 a few days ago, we share the thought that we need to abstract the implementation so it works with LocalRest too.

I applied abstraction for the LocalRest with the support of @AndrejMitrovic.

Relates #1051

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
There is a way to move all the routines into the test module so we don't add unnecessary test-specific code-paths in the base classes.

It's a little bit more complex because we have to forward a lot of calls and make some code in NetworkClient reusable, but it is possible. Here's my approach:

```diff
diff --git a/source/agora/api/FullNode.d b/source/agora/api/FullNode.d
index 75204486..292bebe8 100644
--- a/source/agora/api/FullNode.d
+++ b/source/agora/api/FullNode.d
@@ -70,21 +70,6 @@ public interface API
 // The REST generator requires @safe methods
 @safe:
 
-    /***************************************************************************
-
-        Register the given address to listen for gossiping messages.
-
-        Params:
-            address = the address of the node to register
-
-        API:
-            PUT /register_listener_address
-
-    ***************************************************************************/
-
-    @method(HTTPMethod.PUT)
-    version (unittest) public void registerListenerAddress (Address address);
-
     /***************************************************************************
 
         Returns:
diff --git a/source/agora/network/NetworkClient.d b/source/agora/network/NetworkClient.d
index 0a1ed35f..6b047317 100644
--- a/source/agora/network/NetworkClient.d
+++ b/source/agora/network/NetworkClient.d
@@ -42,7 +42,7 @@ mixin AddLogger!();
 class NetworkClient
 {
     /// Whether to throw an exception when attemptRequest() fails
-    private enum Throw
+    protected enum Throw
     {
         ///
         No,
@@ -69,7 +69,7 @@ class NetworkClient
     private BanManager banman;
 
     /// API client to the node
-    private API api;
+    protected API api;
 
     /// Reusable exception
     private Exception exception;
@@ -115,25 +115,7 @@ class NetworkClient
 
     public PublicKey getPublicKey ()
     {
-        return this.attemptRequest!(API.getPublicKey, Throw.Yes)();
-    }
-
-    /***************************************************************************
-
-        Register the given address as this node's listener
-
-        Params:
-            address = the address to register
-
-        Throws:
-            `Exception` if the request failed.
-
-    ***************************************************************************/
-
-    version (unittest) public void registerListener (Address address)
-    {
-        return this.attemptRequest!(API.registerListenerAddress, Throw.Yes)
-            (address);
+        return this.attemptRequest!(API.getPublicKey, Throw.Yes)(this.api);
     }
 
     /// Ditto
@@ -181,7 +163,7 @@ class NetworkClient
 
     public NodeInfo getNodeInfo ()
     {
-        return this.attemptRequest!(API.getNodeInfo, Throw.Yes)();
+        return this.attemptRequest!(API.getNodeInfo, Throw.Yes)(this.api);
     }
 
     /***************************************************************************
@@ -206,10 +188,10 @@ class NetworkClient
         {
             // if the node already has this tx, don't send it
             if (this.attemptRequest!(API.hasTransactionHash, Throw.Yes,
-                LogLevel.Trace)(tx_hash))
+                LogLevel.Trace)(this.api, tx_hash))
                 return;
 
-            this.attemptRequest!(API.putTransaction, Throw.No)(tx);
+            this.attemptRequest!(API.putTransaction, Throw.No)(this.api, tx);
         });
     }
 
@@ -229,7 +211,8 @@ class NetworkClient
         {
             this.taskman.runTask(
             {
-                this.attemptRequest!(API.receiveEnvelope, Throw.No)(envelope);
+                this.attemptRequest!(API.receiveEnvelope, Throw.No)(this.api,
+                    envelope);
             });
         }
         catch (Exception ex)
@@ -251,7 +234,7 @@ class NetworkClient
 
     public ulong getBlockHeight ()
     {
-        return this.attemptRequest!(API.getBlockHeight, Throw.Yes)();
+        return this.attemptRequest!(API.getBlockHeight, Throw.Yes)(this.api);
     }
 
     /***************************************************************************
@@ -276,7 +259,7 @@ class NetworkClient
 
     public const(Block)[] getBlocksFrom (ulong block_height, uint max_blocks)
     {
-        return this.attemptRequest!(API.getBlocksFrom, Throw.Yes)(
+        return this.attemptRequest!(API.getBlocksFrom, Throw.Yes)(this.api,
             block_height, max_blocks);
     }
 
@@ -297,7 +280,8 @@ class NetworkClient
     {
         this.taskman.runTask(
         {
-            this.attemptRequest!(API.enrollValidator, Throw.No)(enroll);
+            this.attemptRequest!(API.enrollValidator, Throw.No)(this.api,
+                enroll);
         });
     }
 
@@ -318,7 +302,8 @@ class NetworkClient
     {
         this.taskman.runTask(
         {
-            this.attemptRequest!(API.receivePreimage, Throw.No)(preimage);
+            this.attemptRequest!(API.receivePreimage, Throw.No)(this.api,
+                preimage);
         });
     }
 
@@ -342,19 +327,19 @@ class NetworkClient
 
     ***************************************************************************/
 
-    private auto attemptRequest (alias endpoint, Throw DT,
-        LogLevel log_level = LogLevel.Trace, Args...)
-        (auto ref Args args, string file = __FILE__, uint line = __LINE__)
+    protected auto attemptRequest (alias endpoint, Throw DT,
+        LogLevel log_level = LogLevel.Trace, API, Args...)
+        (API api, auto ref Args args, string file = __FILE__, uint line = __LINE__)
     {
         import std.traits;
         enum name = __traits(identifier, endpoint);
-        alias T = ReturnType!(__traits(getMember, this.api, name));
+        alias T = ReturnType!(__traits(getMember, api, name));
 
         foreach (idx; 0 .. this.max_retries)
         {
             try
             {
-                return __traits(getMember, this.api, name)(args);
+                return __traits(getMember, api, name)(args);
             }
             catch (Exception ex)
             {
diff --git a/source/agora/network/NetworkManager.d b/source/agora/network/NetworkManager.d
index 7ad4e033..988f4868 100644
--- a/source/agora/network/NetworkManager.d
+++ b/source/agora/network/NetworkManager.d
@@ -145,7 +145,7 @@ public class NetworkManager
 
         private void connect ()
         {
-            auto client = new NetworkClient(this.outer.taskman,
+            auto client = this.outer.getNetworkClient(this.outer.taskman,
                 this.outer.banman, this.address,
                 this.outer.getClient(this.address,
                     this.outer.node_config.timeout),
@@ -400,11 +400,13 @@ public class NetworkManager
         this.known_addresses.put(node.address);
         this.connection_tasks.remove(node.address);
 
-        // todo: this should keep re-trying.
-        version (unittest)
-            node.client.registerListener(this.getAddress());
-        else
-            node.client.registerListener();
+        this.registerAsListener(node.client);
+    }
+
+    /// Overridable for LocalRest which uses public keys
+    protected void registerAsListener (NetworkClient client)
+    {
+        client.registerListener();
     }
 
     /// Discover the network, connect to all required peers
@@ -712,6 +714,25 @@ public class NetworkManager
         return new RestInterfaceClient!API(settings);
     }
 
+    /***************************************************************************
+
+        Instantiates a networking client to be used with the given API instance.
+
+        Overridable in unittests.
+
+        Returns:
+            a NetworkClient
+
+    ***************************************************************************/
+
+    public NetworkClient getNetworkClient (TaskManager taskman,
+        BanManager banman, Address address, API api, Duration retry,
+        size_t max_retries)
+    {
+        return new NetworkClient(taskman, banman, address, api, retry,
+            max_retries);
+    }
+
     /***************************************************************************
 
         Gossips the transaction to all the listeners.
diff --git a/source/agora/node/FullNode.d b/source/agora/node/FullNode.d
index 70701f95..82bdd190 100644
--- a/source/agora/node/FullNode.d
+++ b/source/agora/node/FullNode.d
@@ -244,13 +244,6 @@ public class FullNode : API
         this.network.registerListener(address);
     }
 
-    /// PUT /register_listener_address
-    version (unittest) public override void registerListenerAddress
-        (Address address) @trusted
-    {
-        this.registerListener(address);
-    }
-
     /// GET: /node_info
     public override NodeInfo getNodeInfo () pure nothrow @safe @nogc
     {
diff --git a/source/agora/test/Base.d b/source/agora/test/Base.d
index 0f2af4f3..3430d356 100644
--- a/source/agora/test/Base.d
+++ b/source/agora/test/Base.d
@@ -42,6 +42,7 @@ import agora.consensus.data.UTXOSetValue;
 import agora.consensus.UTXOSet;
 import agora.consensus.EnrollmentManager;
 import agora.consensus.data.genesis.Test;
+import agora.network.NetworkClient;
 import agora.network.NetworkManager;
 import agora.node.BlockStorage;
 import agora.node.FullNode;
@@ -547,6 +548,36 @@ public class TestAPIManager
     }
 }
 
+/*******************************************************************************
+
+    Adds additional networking capabilities for use in unittests
+
+*******************************************************************************/
+
+public class TestNetworkClient : NetworkClient
+{
+    /// See NetworkClient ctor
+    public this (TaskManager taskman, BanManager banman, Address address,
+        ValidatorAPI api, Duration retry, size_t max_retries)
+    {
+        super(taskman, banman, address, api, retry, max_retries);
+    }
+
+
+    /***************************************************************************
+
+        Throws:
+            `Exception` if the request failed.
+
+    ***************************************************************************/
+
+    public void registerListenerAddress (Address address)
+    {
+        return this.attemptRequest!(TestAPI.registerListenerAddress, Throw.Yes)(
+            cast(TestAPI)this.api, address);
+    }
+}
+
 /*******************************************************************************
 
     Base class for `NetworkManager` used in unittests.
@@ -585,16 +616,25 @@ public class TestNetworkManager : NetworkManager
     }
 
     ///
-    protected final override ValidatorAPI getClient (Address address,
+    protected final override TestAPI getClient (Address address,
         Duration timeout)
     {
         auto tid = this.registry.locate(address);
         if (tid != typeof(tid).init)
-            return new RemoteAPI!ValidatorAPI(tid, timeout);
+            return new RemoteAPI!TestAPI(tid, timeout);
         assert(0, "Trying to access node at address '" ~ address ~
                "' without first creating it");
     }
 
+    ///
+    protected final override TestNetworkClient getNetworkClient (
+        TaskManager taskman, BanManager banman, Address address,
+        ValidatorAPI api, Duration retry, size_t max_retries)
+    {
+        return new TestNetworkClient(taskman, banman, address, api, retry,
+            max_retries);
+    }
+
     /***************************************************************************
 
         Params:
@@ -624,6 +664,13 @@ public class TestNetworkManager : NetworkManager
     {
         assert(0, "Not supported");
     }
+
+    /// Overridable for LocalRest which uses public keys
+    protected final override void registerAsListener (NetworkClient client)
+    {
+        (cast(TestNetworkClient)client).registerListenerAddress(
+            this.node_config.address);
+    }
 }
 
 /*******************************************************************************
@@ -689,6 +736,9 @@ public interface TestAPI : ValidatorAPI
 
     ///
     public QuorumConfig getQuorumConfig ();
+
+    ///
+    public void registerListenerAddress (Address address);
 }
 
 /// Contains routines which are implemented by both TestFullNode and
@@ -773,6 +823,12 @@ private mixin template TestNodeMixin ()
     {
         return new EnrollmentManager(":memory:", node_config.key_pair, params);
     }
+
+    /// Localrest: the address (key) is provided directly to the network manager
+    public override void registerListenerAddress (Address address)
+    {
+        this.network.registerListener(address);
+    }
 }
 
 /// A FullNode which also implements test routines in TestAPI
```

**Comment by AndrejMitrovic** [comment]
You can copy-paste this into a file `diff.diff` and then run `$ git apply diff.diff` and it will apply the patch for you.

**Comment by linked0** [comment]
The `diff` code works so well. I also thought if there was a way to derive `NetworkClient` but I didn't know that the `API` could be a parameter for the `attemptRequest` function. This is the way @AndrejMitrovic apply abstraction for the code.
Thank you.

**Comment by linked0** [comment]
Ping @Geod24

File: source/agora/network/NetworkClient.d [hunk 1]
```diff
@@ -113,24 +115,51 @@ class NetworkClient
...
+                        req.method = HTTPMethod.POST;
+                    },
+                    (scope res) {
+                        if (res.statusCode == 200)
+                            return;
+                        else
+                            log.info("Response of {}/register_listener : {}",
+                                this.address, res);
+                    }
+               );
```
Comment (AndrejMitrovic) [inline source/agora/network/NetworkClient.d]: This is still not exiting early when there was a success. The `return` is inside the delegate, not in the `try/catch`.

File: source/agora/test/Base.d [hunk 2]
```diff
@@ -696,6 +746,23 @@ public interface TestAPI : ValidatorAPI
 
     /// Get the active validator count for the current block height
     public ulong getValidatorCount ();
+
+    /***************************************************************************
+
+        Register the given address to listen for gossiping messages.
+
+        This method is the API endpoint for the LocalRest, which is
```
Comment (AndrejMitrovic) [inline source/agora/test/Base.d]:
```suggestion
        This method is the API endpoint for LocalRest, which is
```

File: source/agora/network/NetworkClient.d [hunk 3]
```diff
@@ -32,6 +32,8 @@ import std.array;
 import std.format;
 import std.random;
 
+import vibe.http.client;
```
Comment (AndrejMitrovic) [inline source/agora/network/NetworkClient.d]: This import should be moved between the `agora` and `std` imports above.

File: source/agora/node/Runner.d [hunk 4]
```diff
@@ -70,6 +71,17 @@ public FullNode runNode (Config config)
         router.registerRestInterface!(agora.api.FullNode.API)(node);
     }
 
+    // Register a path for `register_listener` adding clients' address.
```
Comment (AndrejMitrovic) [inline source/agora/node/Runner.d]:
```suggestion
    // Register a path for `register_listener` adding client's address.
```

`clients'` is used for plural, we're only registering one address though.

**Review by AndrejMitrovic — APPROVED** [review]

**Comment by Geod24** [comment]
Needs a rebase, oLGTM

**Review by Geod24 — APPROVED** [review]

**Comment by Geod24** [comment]
@linked0 : This LGTM, but consistently fails circleci. Could you take a look at it ? I rebased and pushed myself, didn't change your code. But it seems CircleCI didn't like what I did and I can't retrigger a run, but my last 4 pushes didn't pass on it.

**Comment by linked0** [comment]
It seems there's some problem with the code in my PR. Running `ci/system_integration_test.d` failed in my local machine with the log as follows. I will check it from now on.

```
Linking...
To force a rebuild of up-to-date targets, run again with --force.
Running ./tests/system/build/systemtest-simple http://127.0.0.1:4000 http://127.0.0.1:4002 http://127.0.0.1:4003 http://127.0.0.1:4004 http://127.0.0.1:4005 http://127.0.0.1:4006 http://127.0.0.1:4007
core.exception.AssertError@tests/system/source/main.d(41): Check condition failed after timeout of 5 secs and 50 attempts: Node 6 has not completed discovery after 5 secs. 
```

**Comment by AndrejMitrovic** [comment]
@linked0 could you try rebasing your PR one more time?

**Comment by AndrejMitrovic** [comment]
This is going green now.

**Comment by Geod24** [comment]
Merge when green then

**Comment by linked0** [comment]
Wow, it went green in the end. Thanks @AndrejMitrovic!
