### PR TITLE
Fix #888: Remove scope(failure) from valueExternalized (& more)

### LINKED ISSUE #888: Remove `scope (failure) assert(0)` from Nominator.valueExternalized
https://github.com/bpfkorea/agora/blob/35cd603ba7e4e0db798c4b61e31d5ef689041f87/source/agora/consensus/protocol/Nominator.d#L372

Since deserialization can fail, the method has legitimate reasons to error. And it's currently hiding the underlying error, see #886

### PR DESCRIPTION
**Pull request by Geod24**
This scope(failure) was hiding the real issue.
It was originally put there as a quick fix to make the function `nothrow`.
But it ended up hiding why the function was failing
(is the assert triggered or is it a serialization issue?).

### CODE REVIEW

**Comment by Geod24** [comment]
Caught another Exception-eating `scope(failure)` in the Ledger...

**Comment by Geod24** [comment]
Finally:
```console
Full error: core.exception.AssertError@source/agora/node/Ledger.d(233): Assertion failure
----------------
??:? _d_assert [0x10459e2c7]
Ledger.d:233 @safe void agora.node.Ledger.Ledger.addValidatedBlock(ref const(agora.consensus.data.Block.Block)) [0x103c39d33]
Ledger.d:172 @safe bool agora.node.Ledger.Ledger.acceptBlock(ref const(agora.consensus.data.Block.Block)) [0x103c399c9]
Ledger.d:147 @trusted bool agora.node.Ledger.Ledger.onExternalized(agora.consensus.data.ConsensusData.ConsensusData) [0x103c395f4]
Nominator.d:390 _ZN9Nominator17valueExternalizedEyRKN3xdr7xvectorIhLj4294967292EEE [0x103c7971a]
```

https://github.com/bpfkorea/agora/blob/930120de6a8f7020c89fa16ca3f51954d730c8e5/source/agora/node/Ledger.d#L235-L238

**Comment by Geod24** [comment]
Apparently we're trying to add already-enrolled validators:
```
Rejected already existing validator, Data was: const(Enrollment)(0xe1507620b1261d8a444aa555efd1c2cd9a7841c517ae74ae7794dfaaef0051668b5ce8b5299a3428d8e5715108d069530e1fdd5055ef3f1cbfc2b073c5e05a26, 0xb88e19890c18d0dc2237e1c3b07d0d61a56f9955c3f8e18c9e82881b5154c1e5a5bac3ff3044d9284192cfe2e244033ffd3bbb521b66bd838c6e632fc07c274d, 1008, 0x0d66781c79c87ccad9c33e913a3fd8ae63721ff92791bf48849402cf06e93545be87e3d41517608c38fc8fa5fbebd73a6a2520ce028061aeec0ccdddac637801)
```

**Comment by Geod24** [comment]
Bypassing broken CI because this does what it's supposed to.

File: source/agora/consensus/protocol/Nominator.d [hunk 1]
```diff
@@ -367,22 +366,35 @@ extern(D):
...
         if (data.tx_set.length == 0)
             assert(0, "Transaction set empty");
 
         log.info("Externalized consensus data set at {}: {}", slot_idx, data);
-        if (!this.ledger.onExternalized(data))
-            assert(0);
+        try
+        {
+            if (!this.ledger.onExternalized(data))
+                assert(0);
```
Comment (AndrejMitrovic) [inline source/agora/consensus/protocol/Nominator.d:391]: It seems like there should be an `abort` here too instead of the assert?

Comment (Geod24) [reply source/agora/consensus/protocol/Nominator.d:391]: Yeaaaahhhhh... This function now both throws and return a boolean. Will fix.
