### PR TITLE
Flash: Make sure channel updates are gossiped properly

### LINKED ISSUE #2153: Flash layer spurious failure in network tests
```
Module tests failed: agora.test.Flash
core.exception.AssertError@source/agora/test/Flash.d(1348): Rejected
----------------
source/agora/test/Base.d:162 nothrow void agora.test.Base.testAssertHandler(immutable(char)[], ulong, immutable(char)[]) [0x10f4c619f]
core/exception.d:448 onAssertErrorMsg [0x1104e9991]
core/exception.d:590 _d_assert_msg [0x1104e9da5]
source/agora/test/Flash.d:1348 void agora.test.Flash.__unittest_L1217_C1() [0x10f48e2c3]
source/agora/test/Flash.d agora.test.Flash.__unittest [0x10f4a778e]
source/agora/test/Base.d:266 bool agora.test.Base.customModuleUnitTester().runTest(agora.test.Base.customModuleUnitTester().ModTest) [0x10f4c712f]
source/agora/test/Base.d:293 core.runtime.UnitTestResult agora.test.Base.customModuleUnitTester() [0x10f4c59fc]
core/runtime.d:607 runModuleUnitTests [0x110512308]
rt/dmain2.d:552 void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll() [0x11052bfc2]
rt/dmain2.d:526 void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x11052bf42]
rt/dmain2.d:585 _d_run_main2 [0x11052bdfd]
rt/dmain2.d:385 _d_run_main [0x11052bab4]
/Users/runner/hostedtoolcache/dc/ldc2-aeeb90b2/x64/ldc2-aeeb90b2-osx-x86_64/bin/../import/core/internal/entrypoint.d:42 main [0x10f4d23e4]
2021-06-04 08:58:00,846 Error [agora.utils.Utility] - Operation timed out: : Request timed-out
Single threaded test failed early. Only 51/111 tests have been run
```

### PR DESCRIPTION
**Pull request by omerfirmak**
this should fix https://github.com/bosagora/agora/issues/2153#issuecomment-854831875

### CODE REVIEW

File: source/agora/test/Flash.d [hunk 1]
```diff
@@ -254,7 +254,10 @@ public class TestFlashNode : ThinFlashNode, TestFlashAPI
     ///
     public override void waitForChannelDiscovery (in Hash chan_id)
     {
-        while (chan_id !in this.known_channels)
+        // Wait for discovery and first set of updates
+        while ( chan_id !in this.known_channels ||
```
Comment (Geod24) [inline source/agora/test/Flash.d]: Nit: no space after opening parenthesis

File: source/agora/test/Flash.d [hunk 2]
```diff
@@ -220,7 +220,11 @@ public class TestFlashNode : ThinFlashNode, TestFlashAPI
         auto peer = new RemoteAPI!TestFlashAPI(tid, timeout);
         this.known_peers[peer_pk] = peer;
         if (this.known_channels.length > 0)
+        {
             peer.gossipChannelsOpen(this.known_channels.values);
+            peer.gossipChannelUpdates(this.channel_updates.byValue
+                .map!(updates => updates.byValue.array).joiner.array);
```
Comment (Geod24) [inline source/agora/test/Flash.d]: That's a lot of array call... Couldn't the function take a range ?
Additionally, I assume those will not be combined into a single request ?

**Review by Geod24 — APPROVED** [review]
