### PR TITLE
Prevent possible crashes about handlers on shutting down

### LINKED ISSUE #3079: Check if we need to set the array of timers to null
This cannot prevent accessing the array after it being `null` because the flow could already be in the `foreach`, for example. So it would be better to not set `null` to the arrays in the `shutdown` as not setting `null` to the arrays makes no harm, I think.

_Originally posted by @linked0 in https://github.com/bosagora/agora/pull/3078#discussion_r810819032_

### PR DESCRIPTION
**Pull request by linked0**
This prevents a node from crashing when it accesses the event handlers while it's shutting down.

Fixes #3079, #2942

### CODE REVIEW

File: source/agora/node/FullNode.d [hunk 1]
```diff
@@ -1205,8 +1205,6 @@ public class FullNode : API
 
     private void pushBlock (const Block block) @trusted
     {
-        if (this.is_shutting_down)
-            return;
```
Comment (hewison-chris) [inline source/agora/node/FullNode.d:1216]: Why not keep this anyway? We are shutting down so no need to continue.

Comment (linked0) [reply source/agora/node/FullNode.d:1216]: I thought as you do but I think it's not so big impact because it could do only one iteration even if it enters the `foreach` scope. But it's better to keep it.

File: source/agora/node/FullNode.d [hunk 2]
```diff
@@ -1205,27 +1205,32 @@ public class FullNode : API
...
                 continue;
 
             this.taskman.runTask({
                 // Work around potential DMD bug
                 const idx = index;
+                if (this.block_handlers.length <= idx)
+                    return;
+
+                auto _handler = this.block_handlers[idx];
+
```
Comment (hewison-chris) [inline source/agora/node/FullNode.d]: You can remove these other changes now as if not shutting down the array will not be null.

**Review by hewison-chris — CHANGES_REQUESTED** [review]
I think moving the check for shutting down is sufficient to prevent the chance of crashing.

File: source/agora/node/FullNode.d (hunk 2 above)
Comment (linked0) [reply source/agora/node/FullNode.d]: It's for accessing the `this.block_handlers` after the variable has been set to null which means the handler is an empty array. This is kind of related to #2942.

**Review by hewison-chris — APPROVED** [review]
LGTM

**Comment by linked0** [comment]
This PR is continuously failing on CI since last Friday, especially on `ValidatorRecurringEnrollment`. I think the failure is totally unrelated to this PR. So this can be merged. @hewison-chris Can you merge this if you agree with me?

The failure logs are as follows. This failure also happens frequently on other PRs.
```
Module tests failed: agora.test.ValidatorRecurringEnrollment
core.exception.AssertError@source/agora/test/Base.d(797): Check condition failed after timeout of 10 secs and 100 attempts: Client #3 (agora://10.0.0.3/) has no preimage for client #2 (agora://10.0.0.2/) at height 21
```
and
```
Module tests failed: agora.test.ValidatorRecurringEnrollment
core.exception.AssertError@source/agora/test/ValidatorRecurringEnrollment.d(134): Check condition failed after timeout of 10 secs and 100 attempts: Node 0 has block height 21. Expected: 22
----------------
source/agora/utils/Utility.d:146 void agora.utils.Utility.retryFor(lazy bool, core.time.Duration, lazy immutable(char)[], immutable(char)[], ulong) [0x5632b5e7afbf]
<OMITTED>
source/agora/test/ValidatorRecurringEnrollment.d:134 void agora.test.ValidatorRecurringEnrollment.__unittest_L85_C1() [0x5632b63d08ee]
```

**Comment by hewison-chris** [comment]
> This PR is continuously failing on CI since last Friday, especially on `ValidatorRecurringEnrollment`. I think the failure is totally unrelated to this PR. So this can be merged. @hewison-chris Can you merge this if you agree with me?
> 
> The failure logs are as follows. This failure also happens frequently on other PRs.
> 
> ```
> Module tests failed: agora.test.ValidatorRecurringEnrollment
> core.exception.AssertError@source/agora/test/Base.d(797): Check condition failed after timeout of 10 secs and 100 attempts: Client #3 (agora://10.0.0.3/) has no preimage for client #2 (agora://10.0.0.2/) at height 21
> ```
> 
> and
> 
> ```
> Module tests failed: agora.test.ValidatorRecurringEnrollment
> core.exception.AssertError@source/agora/test/ValidatorRecurringEnrollment.d(134): Check condition failed after timeout of 10 secs and 100 attempts: Node 0 has block height 21. Expected: 22
> ```

I have started to look into why these `ValidatorRecurringEnrollment` tests are failing and hope to solve it today. If you really think we need the changes in this PR to be merged then can you add a commit to just skip the two failing tests?  Then we can make sure all the other tests that run after them are still passing.

**Comment by linked0** [comment]
This is an important and simple bug fix but this fails constantly on `ValidatorRecurringEnrollment` which is not related to this PR. Fixing the failure for the test might need more time so I'm merging it with one approval.
