### PR TITLE
Registry: Implement SOA query support

### LINKED ISSUE #2448: Registry: Return SOA records for authoritative zones
Otherwise DNS recursion doesn't work.

### PR DESCRIPTION
**Pull request by mkykadir**
Fixes #2448 

Adds support for SOA queries. Zone serial is updated when data is **really** updated or a record is removed from database.

Note:
Currently SOA query is not checking for Zone configuration if its authoritative, because current configuration parameters are not enough (secondaries are also authoritative, only resolvers are not authoritative)

### CODE REVIEW

File: source/agora/api/Registry.d [hunk 1]
```diff
@@ -30,6 +32,14 @@ public struct RegistryPayloadData
...
     /// monotonically increasing sequence number
     public ulong seq;
+
+    /// Compares payload data, ignores `seq` and permutations of `addresses` 
+    ///   are consiederd equal
+    bool opEquals (in RegistryPayloadData other) const @safe
+    {
+        return (this.public_key == other.public_key)
+            && (this.addresses.isPermutation(other.addresses));
+    }
```
Comment (Geod24) [inline source/agora/api/Registry.d]: If we implement `opEquals`, we generally implement `opCmp` as well.

File: source/agora/api/Registry.d [hunk 2]
```diff
@@ -30,6 +32,14 @@ public struct RegistryPayloadData
 
     /// monotonically increasing sequence number
     public ulong seq;
+
+    /// Compares payload data, ignores `seq` and permutations of `addresses` 
+    ///   are consiederd equal
```
Comment (Geod24) [inline source/agora/api/Registry.d]: Why the extra indent ? Also typo.

File: source/agora/node/Registry.d [hunk 3]
```diff
@@ -928,6 +939,16 @@ private struct ZoneData
         if (payload.payload.data.addresses.length == 0)
             return;
 
+        if (this.get(payload.payload.data.public_key) == payload)
+        { // Payload is equal to Zone's data, no need to update
```
Comment (Geod24) [inline source/agora/node/Registry.d]: Newline

**Review by Geod24 — APPROVED** [review]
This does three things that could be broken down in their own commits:
- Add an `opEqual` to a `struct`;
- Reply to `SOA` request;
- Avoid overriding payload data when not needed;

Concept LGTM.

File: source/agora/api/Registry.d [hunk 4]
```diff
@@ -30,6 +33,48 @@ public struct RegistryPayloadData
...
+
+            if (this.seq != other.seq)
+                return this.seq < other.seq ? -1 : 1;
+
+            if (this.addresses.length != other.addresses.length)
+                return this.addresses.length < other.addresses.length ? -1 : 1;
+            
+            foreach (thisAddr, otherAddr; this.addresses.zip(other.addresses))
+            {
+                auto comparison = cmp(thisAddr.toString, otherAddr.toString);
```
Comment (Geod24) [inline source/agora/api/Registry.d]: Let's avoid `toString` as it allocates

File: source/agora/api/Registry.d [hunk 5]
```diff
@@ -30,6 +33,48 @@ public struct RegistryPayloadData
...
+                // will eventually find non-equal addresses since opEquals failed
+                if (comparison == 0) continue;
+                return comparison;
```
Comment (Geod24) [inline source/agora/api/Registry.d]:
```D
if (auto c = cmp(...))
    return c;
```

File: source/agora/node/Registry.d [hunk 6]
```diff
@@ -833,6 +842,7 @@ private struct ZoneData
             return Header.RCode.NameError;
 
         reply.answers ~= payload.toRR(question.qname);
+        reply.authorities ~= this.toRR(); // optional
```
Comment (Geod24) [inline source/agora/node/Registry.d:845]: I think most servers don't include this, but reading the RFC, this looks correct.

**Review by Geod24 — APPROVED** [review]
Just the allocation.

**Review by Geod24 — APPROVED** [review]
Merge at will
