### PR TITLE
Validator: Only try to re-enroll for recent blocks

### LINKED ISSUE #1546: Eliminate unnecessary Enrollment requests during catch up.
If a Validator is N blocks behind the network, it will try to enroll N times during catch up and fail. Validator should not emit unnecessary requests when it knows that will fail for sure.

### PR DESCRIPTION
**Pull request by omerfirmak**
Fixes #1546

### CODE REVIEW

File: source/agora/node/Validator.d [hunk 1]
```diff
@@ -597,6 +620,6 @@ public class Validator : FullNode, API
         // Network needs Validators, see if we can enroll
         if (this.config.validator.recurring_enrollment &&
             msg == Ledger.InvalidConsensusDataReason.NotEnoughValidators)
-            this.checkAndEnroll(this.ledger.getBlockHeight());
+            this.checkAndEnroll(this.ledger.getBlockHeight(), true);
```
Comment (linked0) [inline source/agora/node/Validator.d]: Can you explain why this calling has `true` for `dont_wait`?

Comment (omerfirmak) [reply source/agora/node/Validator.d]: The case here is that we don't have enough validators for the next round. To get out of that situation faster we ignore the timeout.

File: source/agora/node/Validator.d [hunk 2]
```diff
@@ -553,8 +557,27 @@ public class Validator : FullNode, API
...
+                block_height + 1);
+
+            // Disable existing timer
+            if (emitter)
+                emitter.stop();
+
+            // Network tests use 1 second block interval, timeout should be
+            // adjusted accordingly
+            version (unittest) enum EnrollmentDelay = 10.msecs;
+            else enum EnrollmentDelay = 10.seconds;
```
Comment (Geod24) [inline source/agora/node/Validator.d]: That's a bit red flag

File: source/agora/node/Validator.d [hunk 3]
```diff
@@ -533,11 +533,15 @@ public class Validator : FullNode, API
...
             block_height = Current block height
+            dont_wait = Immediately send the request.
 
     ***************************************************************************/
 
-    protected void checkAndEnroll (Height block_height) @safe
+    protected void checkAndEnroll (Height block_height, bool dont_wait = false) @safe
     {
+        // Enrollment emitter
+        static ITimer emitter;
```
Comment (Geod24) [inline source/agora/node/Validator.d]: `static` variables within member functions are evil. Usually the unit of encapsulation is the object, but in this case it's the method, meaning that if we ever have 2 nodes running in the same thread, things will start to fail randomly. I'd recommend to steer clear from them.

File: source/agora/node/Validator.d [hunk 4]
```diff
@@ -553,8 +557,27 @@ public class Validator : FullNode, API
...
+
+            // This timer will fire after EnrollmentDelay. Within that period,
+            // if we decide to request a different enrollment; next call to
+            // `checkAndEnroll` will disable this. This way we wont flood the
+            // network with invalid enrollment requests
+            () @trusted {
+                emitter = this.taskman.setTimer(dont_wait ? 0.msecs : EnrollmentDelay,
+                    {this.network.peers.each!(p => p.client.sendEnrollment(enrollment));}, 
+                    Periodic.No);
+            } ();
```
Comment (Geod24) [inline source/agora/node/Validator.d]: So you essentially want to turn this into a "daemon" that gets periodically called and checks if it needs to enroll, right ? In which case taking the timer logic out of the function might be the best approach.

File: source/agora/node/Validator.d (hunk 2 above)
Comment (ferencdg) [inline source/agora/node/Validator.d]: I think we still try to retrieve 1024 blocks at once, so that probably needs to be changed too, otherwise 10secs might not be enough :)

File: source/agora/node/Validator.d (hunk 4 above)
Comment (omerfirmak) [reply source/agora/node/Validator.d]: Not really, it is a one shot timer. What I wanted is essentially a delayed and cancelable task.

File: source/agora/node/Validator.d (hunk 2 above)
Comment (omerfirmak) [reply source/agora/node/Validator.d]: I just checked, nodes ask for 1024 blocks but they only return `MaxBatchBlocksSent` which is 20.

**Comment by omerfirmak** [comment]
Updated with the `time_offset` approach

**Review by AndrejMitrovic — APPROVED** [review]

**Review by Geod24 — APPROVED** [review]
