### PR TITLE
Fixed nomination bug caused by missing validators

### LINKED ISSUE #2152: Invalid consensus data assertion being triggered
```
Unittesting agora.test.NetworkClient================================ ASSERT HANDLER ===============================
[source/agora/consensus/protocol/Nominator.d:1151] Assertion thrown during test: combineCandidates: Invalid consensus data: The list of missing validators does not match with the local one. [0] != []
/Users/runner/work/agora/agora/source/agora/consensus/protocol/Nominator.d:1151 int agora.consensus.protocol.Nominator.Nominator.combineCandidates(core.stdc.config.__c_ulonglong, ref const(scpd.Cpp.set!(scpd.Cpp.shared_ptr!(scpd.scp.SCPDriver.ValueWrapper).shared_ptr, scpd.scp.SCPDriver.WrappedValuePtrComparator, scpd.Cpp.allocator!(scpd.Cpp.shared_ptr!(scpd.scp.SCPDriver.ValueWrapper).shared_ptr).allocator).set)).__foreachbody4(ref const(scpd.Cpp.shared_ptr!(scpd.scp.SCPDriver.ValueWrapper).shared_ptr)) [0x10df7e104]
/Users/runner/work/agora/agora/source/scpd/Cpp.d:222 _ZNSt3__13setINS_10shared_ptrIN7stellar12ValueWrapperEEENS2_25WrappedValuePtrComparatorENS_9allocatorIS4_EEE7opApply7wrapperEPvRKS4_ [0x10dc41c16]
??:? _Z15cpp_set_foreachINSt3__110shared_ptrIN7stellar12ValueWrapperEEEEiPvS5_S5_ [0x10e6c7352]
/Users/runner/work/agora/agora/source/scpd/Cpp.d:225 const int scpd.Cpp.set!(scpd.Cpp.shared_ptr!(scpd.scp.SCPDriver.ValueWrapper).shared_ptr, scpd.scp.SCPDriver.WrappedValuePtrComparator, scpd.Cpp.allocator!(scpd.Cpp.shared_ptr!(scpd.scp.SCPDriver.ValueWrapper).shared_ptr).allocator).set.opApply(scope int delegate(ref const(scpd.Cpp.shared_ptr!(scpd.scp.SCPDriver.ValueWrapper).shared_ptr))) [0x10dc41bcc]
/Users/runner/work/agora/agora/source/agora/consensus/protocol/Nominator.d:1141 _ZN9Nominator17combineCandidatesEyRKNSt3__13setINS0_10shared_ptrIN7stellar12ValueWrapperEEENS3_25WrappedValuePtrComparatorENS0_9allocatorIS5_EEEE [0x10dcbc0f3]
??:? _ZN7stellar18NominationProtocol15processEnvelopeENSt3__110shared_ptrINS_18SCPEnvelopeWrapperEEE [0x10e7232c8]
??:? _ZN7stellar4Slot15processEnvelopeENSt3__110shared_ptrINS_18SCPEnvelopeWrapperEEEb [0x10e785346]
??:? _ZN7stellar3SCP15receiveEnvelopeENSt3__110shared_ptrINS_18SCPEnvelopeWrapperEEE [0x10e76b62c]
/Users/runner/work/agora/agora/source/agora/consensus/protocol/Nominator.d:575 @trusted void agora.consensus.protocol.Nominator.Nominator.receiveEnvelope(in ref scpd.types.Stellar_SCP.SCPEnvelope) [0x10dcbeb78]
/Users/runner/work/agora/agora/source/agora/node/Validator.d:356 @safe void agora.node.Validator.Validator.receiveEnvelope(scpd.types.Stellar_SCP.SCPEnvelope) [0x10dcb6c2e]
/Users/runner/work/agora/agora/submodules/localrest/source/geod24/LocalRest.d-mixin-667:684 void geod24.LocalRest.RemoteAPI!(agora.test.Base.TestAPI, agora.test.Base.Serializer).RemoteAPI.handleCommand(geod24.LocalRest.Command, agora.test.Base.TestAPI, geod24.LocalRest.FilterAPI, geod24.concurrency.Channel!(geod24.LocalRest.Response).Channel) [0x10dd9d81a]
/Users/runner/work/agora/agora/submodules/localrest/source/geod24/LocalRest.d:801 void geod24.LocalRest.RemoteAPI!(agora.test.Base.TestAPI, agora.test.Base.Serializer).RemoteAPI.spawned!(agora.test.Base.TestValidatorNode).spawned(geod24.concurrency.Channel!(geod24.LocalRest.Connection).Channel, immutable(char)[], int, agora.common.Config.Config, shared(geod24.Registry.Registry!(agora.test.Base.TestAPI).Registry)*, shared(geod24.Registry.Registry!(agora.registry.API.NameRegistryAPI).Registry)*, immutable(agora.consensus.data.Block.Block)[], in ref agora.test.Base.TestConf, shared(ulong)*).runNode().__lambda4().__lambda14() [0x10ddb27e4]
context.d:46 void core.thread.context.Callable.opCall() [0x10eddef9e]
fiber.d:1129 void core.thread.fiber.Fiber.run() [0x10eddf12d]
fiber.d:186 fiber_entryPoint [0x10eddf062]
```

Another ConsensusData resolution issue that needs to be addressed.

### PR DESCRIPTION
**Pull request by ferencdg**
Previously the change in the missing validators caused our SCP votes to
change from 'Yes' to 'No' triggering asserts in the SCP code. This has
been fixed by introducing lower and upper bound of acceptable missing
validators.

fixes: #2152

### CODE REVIEW

File: source/agora/node/Ledger.d [hunk 1]
```diff
@@ -2178,7 +2194,45 @@ unittest
...
+    auto no_fee_txs = blocks[$-1].spendable.map!(txb => txb.sign()).array();
+    no_fee_txs.each!(tx => assert(ledger.acceptTransaction(tx)));
+
+    ConsensusData data;
+    ledger.prepareNominatingSet(data, Block.TxsInTestBlock, mock_clock.networkTime());
+
+    assert(ledger.validateConsensusData(data, skip_indexes) is null);
+
+    data.missing_validators = [2,5,7];
+    assert(ledger.validateConsensusData(data, [2,5,7,9]) is null);
```
Comment (hewison-chris) [inline source/agora/node/Ledger.d]:
```suggestion
    assert(ledger.validateConsensusData(data, [2,3,5,7,9]) is null);
```

Comment (hewison-chris) [reply source/agora/node/Ledger.d]: Not sure this will pass but I think it should.

**Review by hewison-chris — COMMENTED** [review]
I am not really understanding the lower and upper bounds.

**Comment by ferencdg** [comment]
> I am not really understanding the lower and upper bounds.

The idea here is that, the previous way of implementing what is considered 'acceptable candidate regarding missing validators' was too strict. Instead of equality, NodeA will check the candidate from NodeB in the following way:

Current missing validators in NodeA(=X) ⊆ missing validators in the candidate from NodeB(=Y) ⊆ missing validators in NodeA before the nomination round started(=Z)

If both of those conditions true, then NodeA will accept the candidate.

As the nodes exchanges preimages througout nomination(implemented in a separate ticket), the X and Y will both converge to [] or at least a stable set of missing validators, so:
1. the nomination round will end and not last forever
2. nodes don't change their votes from 'Yes' to 'No' ('No' to 'Yes' still happens, but that is fine in SCP as far as I know and we already rely on that fact with missing transactions)

File: source/agora/node/Ledger.d (hunk 1 above)
Comment (ferencdg) [reply source/agora/node/Ledger.d]: here we are testing: 
[2,5] ⊆ [2,5,7] ⊆ [2,5,7,9] , so of course your suggestion would also pass

[2,5] ⊆ [2,5,7] ⊆ [2,3,5,7,9], but I think no need to change the code

File: source/agora/consensus/protocol/Nominator.d [hunk 2]
```diff
@@ -409,14 +412,17 @@ extern(D):
             return;
         }
 
-        if (this.nomination_start_time == 0)
+        if (!this.is_nominating)
```
Comment (linked0) [inline source/agora/consensus/protocol/Nominator.d:415]: I think this is an unrelated change.

File: source/agora/node/Ledger.d (hunk 1 above)
Comment (linked0) [inline source/agora/node/Ledger.d]: I think the two calls of `validateConsensusData` including the above one are called on different nodes. So it should be commented, which is kind of confusing.

File: source/agora/node/Ledger.d [hunk 3]
```diff
@@ -1236,31 +1244,39 @@ public class Ledger
...
+        auto sorted_missing_validators = missing_validators.dup().sort();
+        auto sorted_missing_validators_lower_bound = missing_validators_lower_bound.dup().sort();
+        auto sorted_missing_validators_higher_bound = missing_validators_higher_bound.dup().sort();
 
-        if (local_missing_validators != missing_validators)
-            return "The list of missing validators does not match with the local one. " ~
-                assumeWontThrow(to!string(missing_validators)) ~
-                " != " ~ assumeWontThrow(to!string(local_missing_validators));
+        if (!startsWith(sorted_missing_validators, sorted_missing_validators_lower_bound))
+            return "Missing validator mismatch " ~
```
Comment (linked0) [inline source/agora/node/Ledger.d]: In the message, you should add additional text like "lower bound" and "current missing validators".

File: source/agora/node/Ledger.d [hunk 4]
```diff
@@ -1236,31 +1244,39 @@ public class Ledger
...
+                assumeWontThrow(to!string(sorted_missing_validators_lower_bound)) ~
+                " is not a subset of " ~ assumeWontThrow(to!string(sorted_missing_validators));
+
+        if (!startsWith(sorted_missing_validators_higher_bound, sorted_missing_validators))
+            return "Missing validator mismatch " ~
```
Comment (linked0) [inline source/agora/node/Ledger.d]: In the message, you should add additional text like "higher bound" and "current missing validators".

**Review by linked0 — COMMENTED** [review]
Good work, some comments.

File: source/agora/consensus/protocol/Nominator.d (hunk 2 above)
Comment (ferencdg) [reply source/agora/consensus/protocol/Nominator.d:415]: > I think this is an unrelated change.

it is related, I had to start using that boolean to decide if the nomination round has started or not to be consistent with the code a couple of lines below

Comment (linked0) [reply source/agora/consensus/protocol/Nominator.d:415]: > I think this is an unrelated change.

Sorry for the wrong impression. I meant it's not directly related to checking the lists of missing validators. So it should be on another commit. Doesn't it succeed with the original line?

Comment (ferencdg) [reply source/agora/consensus/protocol/Nominator.d:415]: this line was added because of the subset change:
https://github.com/bosagora/agora/pull/2235/files#diff-2c5fcbf7251215d5e7aba3eaa09c23da9d88c3645e5c278b9ef351b9798184f7R423

and the line you commented was changed to be consistent with the line I referenced above

File: source/agora/node/Ledger.d (hunk 1 above)
Comment (hewison-chris) [reply source/agora/node/Ledger.d]: > here we are testing:
> [2,5] ⊆ [2,5,7] ⊆ [2,5,7,9] , so of course your suggestion would also pass
> 
> [2,5] ⊆ [2,5,7] ⊆ [2,3,5,7,9], but I think no need to change the code

Are you sure? The reason why I suggested the change is I suspected it would fail with the current implementation.

Comment (hewison-chris) [reply source/agora/node/Ledger.d]: I just checked locally and the test fails with the change. The reason being that the `startsWith` is not same as sub set check.

Comment (ferencdg) [reply source/agora/node/Ledger.d]: sorry, I misunderstood, I thought you have a problem with the test. Yes the implementation of the subset had a bug, thanks.

File: source/agora/node/Ledger.d [hunk 5]
```diff
@@ -1236,31 +1244,41 @@ public class Ledger
     ***************************************************************************/
 
     private string isInvalidPreimageRootReason (in Height height,
-        in uint[] missing_validators) @safe nothrow
+        in uint[] missing_validators, in uint[] missing_validators_higher_bound) @safe nothrow
```
Comment (hewison-chris) [inline source/agora/node/Ledger.d:1247]: IMO it is less confusing if you name this `initial_missing_validators`.

File: source/agora/node/Ledger.d [hunk 6]
```diff
@@ -1236,31 +1244,41 @@ public class Ledger
...
     {
+        import std.algorithm.setops : setDifference;
+
         Hash[] keys;
         if (!this.enroll_man.getEnrolledUTXOs(height, keys) || keys.length == 0)
             assert(0, "Could not retrieve enrollments / no enrollments found");
 
-        uint[] local_missing_validators;
+        uint[] missing_validators_lower_bound;
```
Comment (hewison-chris) [inline source/agora/node/Ledger.d:1255]: Also here keep the original name.

**Review by hewison-chris — CHANGES_REQUESTED** [review]
LGTM but I think `local_missing` must be subset of `received_missing` must be subset of `initial_missing` should be more clearly documented. The higher and lower bounds just confused me.

File: source/agora/node/Ledger.d [hunk 7]
```diff
@@ -2178,7 +2196,45 @@ unittest
...
+    assert(ledger.validateConsensusData(data, skip_indexes) is null);
+
+    data.missing_validators = [2,5,7];
+    assert(ledger.validateConsensusData(data, [2,3,5,7,9]) is null);
+
+    data.missing_validators = [2,5];
+    assert(ledger.validateConsensusData(data, [2]) == "Higher bound violation - Missing validator mismatch [2, 5] is not a subset of [2]");
+
+    data.missing_validators = [5];
+    assert(ledger.validateConsensusData(data, [2]) == "Lower bound violation - Missing validator mismatch [2, 5] is not a subset of [5]");
```
Comment (linked0) [inline source/agora/node/Ledger.d:2229]: There are four `validateConsensusData` calls so it would be good to explain the concept of each call.

**Review by linked0 — COMMENTED** [review]
On the contrary to @hewison-chris'  opinion, the concept of `higher` or `lower` bounds looks good to me because it adds some more meaning to the variables if we know that `initial missing validators` is used for `higher bound` and `current missing validators` for `lower bound`. Let's hear others' opinions.

**Comment by ferencdg** [comment]
ready for merge

added docs as Chris suggested, but kept the variable names - with the docs it is easier to undersand without changing the variable names (at least I think)

File: source/agora/node/Ledger.d [hunk 8]
```diff
@@ -1236,31 +1244,54 @@ public class Ledger
...
         }
 
-        if (local_missing_validators != missing_validators)
-            return "The list of missing validators does not match with the local one. " ~
-                assumeWontThrow(to!string(missing_validators)) ~
-                " != " ~ assumeWontThrow(to!string(local_missing_validators));
+        // The idea here is that, the previous way of implementing what is
+        // considered 'acceptable candidate regarding missing validators'
+        // was too strict. Instead of equality, NodeA will check the candidate
+        // from NodeB in the following way:
```
Comment (Geod24) [inline source/agora/node/Ledger.d]: Context fades, and any documentation relying on too much context will eventually become problematic.
Which is why documenting a functionality based on a (assumedly known) previous state is not future-proof.
If you want to mention the previous state, do so explicitly:
> A previous implementation that was simply checking that the local node's missing validators
> was equal to the one received was inadequate because [...]

Or simply document the state of things as it is now:
> NodeA will check the candidate [...]

I do think it's good to mention why a simple equality check is not a good idea, but the rationale should be provided.

**Review by Geod24 — APPROVED** [review]
Nice, just one issue w.r.t. doc

File: source/agora/node/Ledger.d (hunk 8 above)
Comment (ferencdg) [reply source/agora/node/Ledger.d]: fixed the doc
