### PR TITLE
Network section in config shouldn't be mandatory

### LINKED ISSUE #1536: Network section in config shouldn't be mandatory
currently if the network section is empty, agora exits with: 
`Failed to parse config file 'config.yaml'. Error: The 'network' section is mandatory and must specify at least one item`

However if we have a name registry set up, then the network section shouldn't be mandatory.

### PR DESCRIPTION
**Pull request by ferencdg**
If a validator node has a name registry in the config, then
the network section can be empty.

This is a pre-requisite for infra #99

fixes: #1536

### CODE REVIEW

**Review by AndrejMitrovic — APPROVED** [review]

File: source/agora/common/Config.d [hunk 1]
```diff
@@ -356,13 +383,15 @@ private Config parseConfigImpl (in CommandLine cmdln, Node root)
...
+        network : assumeUnique(parseSequence("network", cmdln, root, true)),
         dns_seeds : assumeUnique(parseSequence("dns", cmdln, root, true)),
         logging: parseLoggingSection("logging" in root, cmdln),
         event_handlers: parserEventHandlers("event_handlers" in root, cmdln),
     };
 
-    enforce(conf.network.length > 0, "Network section is empty");
+    enforce((conf.network.length > 0) ||
+            (conf.validator.enabled && conf.validator.registry_address != "disabled"),
+         "Network section is empty");
```
Comment (Geod24) [inline source/agora/common/Config.d]:
```suggestion
    if (conf.validator.enabled)
        enforce(conf.network.length || conf.validator.registry_address != "disabled",
            "Either the network section must not be empty, or 'validator.registry_address' must be set");
    else
        enforce(conf.network.length, "Network section must not be empty");    
```

This should provide a slightly better user experience.

**Review by Geod24 — APPROVED** [review]
Nice. Just a nitpick on  the error message.

**Review by Geod24 — APPROVED** [review]

**Review by kchulj — APPROVED** [review]
