### PR TITLE
Fee: Make validator shares worth a fixed amount

### LINKED ISSUE #2240: TX fee calculation vulnerability
One validator can cause all the transaction fees to go to the Foundation and prevent other validators including itself to receive any transaction fee.

The validator can chose a prime number greater than 40000 Boa(40000.000_000_0) like the following
40000.000_001_9

If the total tx fee for the block was less then 40000 BOA and we have at least 1 validator whose stake is a relative prime to 40000.000_001_9 (reasonable assumption), then the tx fee will be 0

```D
        Amount share_stake = Amount.gcd(stake_amounts);
        // Total "share" count staked
        const total_shares = sum_stake.count(share_stake);

        // tx_fees now equals "share value"
        tx_fees.div(total_shares);
```

### PR DESCRIPTION
**Pull request by omerfirmak**
Now Validators will have to stake a minimum additional
amount to get a bigger share from the fees of a block.

Fixes #2240

### CODE REVIEW

**Comment by kchulj** [comment]
The logic LGTM. Are there any tests for this?

**Review by hewison-chris — APPROVED** [review]
LGTM

**Review by kchulj — APPROVED** [review]
LGTM

**Comment by omerfirmak** [comment]
> 
> 
> The logic LGTM. Are there any tests for this?

I made small changes to existing tests and that should be enough.

File: source/agora/consensus/Fee.d [hunk 1]
```diff
@@ -297,22 +298,20 @@ public class FeeManager
...
         tx_fees.percentage(this.params.ValidatorTXFeeCut);
 
-        Amount sum_stake;
-        Amount[] stake_amounts = stakes.map!(utxo => utxo.output.value).array;
-        stake_amounts.each!(stake => sum_stake += stake);
+        // A Validator with MinFreezeAmount of coins staked will get 100 "shares"
+        // this fixes the stake amount that is needed to get a share
+        Amount share_stake = Amount.MinFreezeAmount;
+        share_stake.div(100);
+        // this will ignore any remaning part of the stake that is not worth a share
```
Comment (Geod24) [inline source/agora/consensus/Fee.d:305]: 👍 for the comment

File: source/agora/consensus/Fee.d [hunk 2]
```diff
@@ -525,10 +524,11 @@ public class FeeManager
         auto utxoset = new TestUTXOSet();
 
         Amount double_stake = Amount.MinFreezeAmount; assert(double_stake.mul(2));
+        Amount stake_with_excess = Amount.MinFreezeAmount; assert(double_stake.add(Amount(19))); // this should not change distribution
```
Comment (Geod24) [inline source/agora/consensus/Fee.d]: Is the `assert` be on `double_stake` or `stake_with_excess` ?

Comment (Geod24) [reply source/agora/consensus/Fee.d]: In any case, you can use the operators overloads here if you want, since it's not testing the addition / multiplication themselves.

File: source/agora/consensus/Fee.d [hunk 3]
```diff
@@ -287,6 +287,7 @@ public class FeeManager
     private Amount[] getValidatorFees (Amount tot_fee, Amount tot_data_fee,
         UTXO[] stakes) nothrow @safe
     {
+        import std.numeric : gcd;
```
Comment (Geod24) [inline source/agora/consensus/Fee.d:290]: Why the direct `gcd` usage instead of `Amount.gdc` ? Is it because `Amount.gcd` doesn't accept a range ?

Comment (omerfirmak) [reply source/agora/consensus/Fee.d:290]: Because they are not `Amount`s anymore. They are plain `ulong`s, shares. `Amount.gcd()` was only used here, we might as well remove it.

**Review by Geod24 — APPROVED** [review]
Sounds good
