### PR TITLE
Ensure errors are handled in getBlocksFrom()

### LINKED ISSUE #127: Random segfault in the tests
Observed on LDC 1.16, Mac OSX:
```
Target /Users/travis/build/bpfkorea/agora/source/scpp/build/libscp.o is up to date, nothing to do
Deserializing composite type ArgWrapper!() which has no serializable fields.
Serializing composite type ArgWrapper!() which has no serializable fields
Running ./build/agora 
0   agora                               0x000000011016b88e _D4core7runtime18runModuleUnitTestsUZ19unittestSegvHandlerUNbiPSQCk3sys5posix6signal9siginfo_tPvZv + 62
1   libsystem_platform.dylib            0x00007fff5baf2f5a _sigtramp + 26
0   agora                               0x000000011016b88e _D4core7runtime18runModuleUnitTestsUZ19unittestSegvHandlerUNbiPSQCk3sys5posix6signal9siginfo_tPvZv + 62
1   libsystem_platform.dylib            0x00007fff5baf2f5a _sigtramp + 26
Program exited with code -11
The command "dub test --skip-registry=all --compiler=${DC}" exited with 2.
```

https://travis-ci.com/bpfkorea/agora/jobs/220748509

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
This might fix https://github.com/bpfkorea/agora/issues/127, but not guaranteed. I'll do several test-runs to confirm.

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
There's one more error-case I need to cover. If `reduce` fails because all the node's failed.

**Comment by AndrejMitrovic** [comment]
Added another commit fixing this case.

File: source/agora/network/NetworkManager.d [hunk 1]
```diff
@@ -200,8 +203,16 @@ public class NetworkManager
     private void getBlocksFrom (ulong block_height,
         scope void delegate(const(Block)[]) @safe onReceivedBlocks)
     {
+        // return size_t.max if getBlockHeight() fails
+        size_t getHeight (NetworkClient node)
+        {
+            size_t height = size_t.max;
+            collectException(node.getBlockHeight(), height);
```
Comment (Geod24) [inline source/agora/network/NetworkManager.d]: I'd prefer a `try` / `catch`

**Review by Geod24 — COMMENTED** [review]
Do you have test cases ?

**Comment by AndrejMitrovic** [comment]
> Do you have test cases ?

Will add.

File: source/agora/network/NetworkManager.d (hunk 1 above)
Comment (AndrejMitrovic) [reply source/agora/network/NetworkManager.d]: Why.

Comment (Geod24) [reply source/agora/network/NetworkManager.d]: `DIP1008`

File: source/agora/test/NetworkManager.d [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+    auto network = makeTestNetwork!TestNetworkManager(NetworkTopology.Simple, NodeCount);
+    network.start();
+    assert(network.getDiscoveredNodes().length == NodeCount);
+
+    auto nodes = network.apis.values;
+    auto node_1 = nodes[0];
+
+    // first two nodes will fail, second two should work
+    nodes[0].filter!(node_1.getBlockHeight);
+    nodes[1].filter!(node_1.getBlockHeight);
```
Comment (Geod24) [inline source/agora/test/NetworkManager.d]: Style nit: Can we go with `API.getBlockHeight` instead of `node_1.gitBlockHeight` ? The former makes it more obvious that the instance is irrelevant.

File: source/agora/network/NetworkManager.d [hunk 3]
```diff
@@ -200,8 +203,16 @@ public class NetworkManager
     private void getBlocksFrom (ulong block_height,
         scope void delegate(const(Block)[]) @safe onReceivedBlocks)
     {
+        // return size_t.max if getBlockHeight() fails
+        size_t getHeight (NetworkClient node)
+        {
+            size_t height = size_t.max;  // if it fails, return max
+            try { height = node.getBlockHeight(); } catch (Exception ex) { }
+            return height;
```
Comment (Geod24) [inline source/agora/network/NetworkManager.d]:
```D
try
    return node.getBlockHeight();
catch (Exception ex)
    return size_t.max;

**Review by Geod24 — COMMENTED** [review]
LGTM minus 2 nits

**Comment by AndrejMitrovic** [comment]
Fixed, let's see if it's eco-friendly.

**Review by Geod24 — APPROVED** [review]

**Comment by Geod24** [comment]
> This might fix #127, but not guaranteed.

Github had so much trust in you
