### PR TITLE
Ledger: Fix active_enrollments underflow

### LINKED ISSUE #1679: integer overflow while validating missing validators
```D
        size_t active_enrollments = enroll_man.getValidatorCount(expect_height);
        assert(active_enrollments >= data.missing_validators.length);
        active_enrollments -= data.missing_validators.length;
        
         if (data.enrolls.length + active_enrollments < Enrollment.MinValidatorCount)
            return InvalidConsensusDataReason.NotEnoughValidators;
```
the condition
active_enrollments >= data.missing_validators.length
is only checked for debug build

if an attacker proposes a candidate with 
data.missing_validators.length > active_enrollments
then active_enrollments will become a very big positive number

### PR DESCRIPTION
**Pull request by omerfirmak**
Fixes #1679

### CODE REVIEW

File: source/agora/node/Ledger.d [hunk 1]
```diff
@@ -600,6 +600,7 @@ public class Ledger
         NotEnoughValidators = "Enrollment: Insufficient number of active validators",
         MayBeValid = "May be valid",
         OnlyCoinbaseTX = "Transaction set only includes a Coinbase transaction",
+        TooManyMPVs = "More MPVs than active enrollments",
```
Comment (Geod24) [inline source/agora/node/Ledger.d:603]: What's MPV ?

Comment (linked0) [reply source/agora/node/Ledger.d:603]: It's an acronym for `Missing Pre-image Validator`. But I think more documentation is needed.

**Review by linked0 — APPROVED** [review]
LGTM

**Review by kchulj — APPROVED** [review]
