### PR TITLE
Fix errors of fee calculation on flash transactions

### LINKED ISSUE #2494: Remove 0 fee special casing in Flash tests
https://github.com/bosagora/agora/blob/b72bd7c2718e33bf962cf90b2453c086dd6fc90c/source/agora/test/Flash.d#L591-L593

This has to go to mimic real-world scenarios.

### PR DESCRIPTION
**Pull request by linked0**
This is a PR in the middle of solving the #2494 which needs some information for the problem that occurs in collecting close transaction signatures. I solved the errors in calculating fees on `funding tx`, `update tx`, and `settle tx`. But in the middle of solving the problem on the `close tx`, I might need to get some clues or prerequisite knowledge from @omerfirmak.

I will open another PR and make the PR fail on the second unit test in source/agora/test/Flash.d intentionally for some discussion. Before that, can you review the code for solving the problem of fee calculation on `funding tx`, `update tx`, and `settle tx`?
 
Fixes #2494

### CODE REVIEW

File: source/agora/flash/Scripts.d [hunk 1]
```diff
@@ -177,7 +177,7 @@ public Unlock createUnlockSettle (Signature sig, in ulong seq_id,
 public Transaction createFundingTx (in UTXO utxo, in Hash utxo_hash,
     in Amount capacity, in Point pair_pk, Amount fee) @safe nothrow
 {
-    auto inputs = [Input(utxo_hash)];
+    auto inputs = [Input(utxo_hash, Unlock(SigPair.init[]))];
```
Comment (omerfirmak) [inline source/agora/flash/Scripts.d:181]: Can you add a small test to verify that:

`createFundingTx(..., fee). getFeeRate()  == fee`

So that we don't break this in the future

File: source/agora/flash/Channel.d [hunk 2]
```diff
@@ -2233,7 +2233,14 @@ LOuter: while (1)
...
         auto update_ouput = update_tx.outputs[0];
 
-        auto utxos = this.getFeeUTXOs(update_tx.sizeInBytes());
+        // calculate fee
+        auto max_size = update_tx.sizeInBytes();
+        auto mock_refund_output = Output(Amount.init, this.own_pk);
+        max_size += mock_refund_output.sizeInBytes();
+        auto mock_update_unlock = this.update_signer.makeUpdateUnlock(SigPair.init, update.seq_id);
+        max_size += mock_update_unlock.sizeInBytes();
+        auto utxos = this.getFeeUTXOs(max_size);
```
Comment (omerfirmak) [inline source/agora/flash/Channel.d:2242]: This is a chicken&egg problem. We can't know how many UTXOs `getFeeUTXOs` will return. So any calculations we do here is an approximation of the TX size. We have to check if our TX size is the same as the expected size after adding fees, or delegate that work to the getFeeUTXOs itself and assume that returned UTXOs are enough to cover the additional inputs and outputs.

File: source/agora/flash/Scripts.d (hunk 1 above)
Comment (linked0) [reply source/agora/flash/Scripts.d:181]: Will add a test for that.

File: source/agora/flash/Channel.d (hunk 2 above)
Comment (linked0) [reply source/agora/flash/Channel.d:2242]: Right, I missed a calculation of the fee for outputs. In fact, the code in `getFeeUTXOs` calculates the fee for inputs. I will add it and check that the returned UTXOs are enough. Thanks.

Comment (linked0) [reply source/agora/flash/Channel.d:2242]: After looking into the code again, the output for the refund of the fee was also calculated as follows.
`
auto mock_refund_output = Output(Amount.init, this.own_pk);
`
So only thing to be needed in this part is to add checking that the returned UTXOs are enough.

File: source/agora/flash/Scripts.d (hunk 1 above)
Comment (linked0) [reply source/agora/flash/Scripts.d:181]: Updated.

File: source/agora/flash/Channel.d (hunk 2 above)
Comment (linked0) [reply source/agora/flash/Channel.d:2242]: Updated.

File: source/agora/flash/Scripts.d [hunk 3]
```diff
@@ -193,7 +194,12 @@ public Transaction createFundingTx (in UTXO utxo, in Hash utxo_hash,
     if (rem_funds > 0.coins)
         outputs ~= Output(rem_funds, utxo.output.lock);
 
-    return Transaction(inputs, outputs);
+    // check the calculated fee for the tx size
+    auto funding_tx = Transaction(inputs, outputs);
+    if (!fee_rate.mul(funding_tx.sizeInBytes()) || fee_rate != fee)
```
Comment (omerfirmak) [inline source/agora/flash/Scripts.d]: Oops, I overlooked something when I left the previous comment. As `max_size` name suggests, we actually might overpay here, if there is no refund output. So the check should be `fee_rate >= fee`.

and let's put this in a `version (unittest)` so that we don't crash for this when running in production.

File: source/agora/flash/Node.d [hunk 4]
```diff
@@ -1418,8 +1419,15 @@ public class FlashNode : FlashControlAPI
             return FeeUTXOs.init;
         // Always pay with the node key
         auto utxos = this.listener.getFeeUTXOs(this.conf.key_pair.address, per_byte);
+
+        // calculate a expected fee for checking the fee is correct
+        per_byte = this.listener.getEstimatedTxFee();
```
Comment (omerfirmak) [inline source/agora/flash/Node.d]: Calling `getEstimatedTxFee` multiple times might result in different values to be returned, so it should only be called once throughout the `getFeeUTXOs`

File: source/agora/flash/Node.d [hunk 5]
```diff
@@ -1418,8 +1419,15 @@ public class FlashNode : FlashControlAPI
...
+        utxos.utxos.each!(hash =>
+            tx_size += Input(hash, genKeyUnlock(SigPair.init)).sizeInBytes());
+        per_byte.mul(tx_size);
+
         // reuse total_value as refund amount
-        if (!utxos.total_value.sub(per_byte))
+        if (!utxos.total_value.sub(utxos.total_fee) || per_byte != utxos.total_fee)
```
Comment (omerfirmak) [inline source/agora/flash/Node.d]: If we are gonna add a new `total_fee` field, don't subtract that from the `total_value`. So that the caller knows how much the UTXO set it received is worth and how much fees it should pay with them. Caller should do the `total_value - total_fee` to properly create the refund output.

File: source/agora/test/Flash.d [hunk 6]
```diff
@@ -569,12 +570,17 @@ private class FlashListener : TestFlashListenerAPI
             foreach (idx, output; tx.outputs)
                 if (output.address() == pk)
                 {
-                    utxos.utxos ~= UTXO.getHash(tx.hashFull(), idx);
+                    auto utxo = UTXO.getHash(tx.hashFull(), idx);
+                    utxos.utxos ~= utxo;
                     utxos.total_value += output.value;
+                    auto per_byte = this.getEstimatedTxFee();
```
Comment (omerfirmak) [inline source/agora/test/Flash.d]: Same comment about the `getEstimatedTxFee`

File: source/agora/flash/Channel.d [hunk 7]
```diff
@@ -2233,7 +2233,14 @@ LOuter: while (1)
         auto update_input = update_tx.inputs[0];
```
Comment (omerfirmak) [inline source/agora/flash/Channel.d:2233]: Typo in commit message "undate"

File: source/agora/flash/Channel.d [hunk 8]
```diff
@@ -777,6 +777,38 @@ LOuter: while (1)
             auto settle_tx = this.channel_updates[$ - 1].settle_tx;
             // point the input to the last update utxo
             settle_tx.inputs[0].utxo = this.last_externalized_update_utxo;
+            auto settle_input = settle_tx.inputs[0];
```
Comment (omerfirmak) [inline source/agora/flash/Channel.d]: Settle txs can't have fees added to them this way. They are not the same with the update TXs. Let's drop this commit from this PR and discuss it on another one after merging the others.

File: source/agora/test/Flash.d [hunk 9]
```diff
@@ -585,21 +590,28 @@ private class FlashListener : TestFlashListenerAPI
...
+private TestConf flashTestConf (bool noFee = true)
 {
     import agora.node.Config;
 
     TestConf conf;
     conf.consensus.quorum_threshold = 100;
-    // TODO: remove this line when fees are handled
-    conf.consensus.min_fee = Amount(0);
-    conf.node.min_fee_pct = 0;
+    if (noFee)
```
Comment (omerfirmak) [inline source/agora/test/Flash.d]: There is no reason to have seperate tests for TXs with/without fees. It also leads to duplicated tests. I would say drop this commit from this PR too.

**Review by omerfirmak — CHANGES_REQUESTED** [review]

File: source/agora/test/Flash.d (hunk 9 above)
Comment (linked0) [reply source/agora/test/Flash.d]: Right, this `if` part is temporary. The goal for issue #2494  is to remove all this `if` part as the comment, `// TODO: remove this line when fees are handled` suggested. My current blocking problem about the issue is to fix the error [the test PR](https://github.com/bosagora/agora/pull/2679) makes. And, we need to fix the problem about `settle tx` also in other way [as you commented](https://github.com/bosagora/agora/pull/2678#discussion_r752095583).
Thank you for the review.

**Comment by linked0** [comment]
I'll refine this PR to drop some commits at this time and will request review again. Let talk about the remaining problems in the issue again. @omerfirmak Thanks :)

File: source/agora/flash/Scripts.d (hunk 3 above)
Comment (linked0) [reply source/agora/flash/Scripts.d]: Updated.

File: source/agora/flash/Channel.d (hunk 7 above)
Comment (linked0) [reply source/agora/flash/Channel.d:2233]: Fixed

File: source/agora/flash/Channel.d (hunk 8 above)
Comment (linked0) [reply source/agora/flash/Channel.d]: Will discuss it next time.

File: source/agora/flash/Node.d (hunk 5 above)
Comment (linked0) [reply source/agora/flash/Node.d]: I agree. So I moved the code to the caller and removed the check code for the expected fee because it's not so useful.

**Comment by linked0** [comment]
Ready for review.
After this is merged, we will discuss how to deal with the fee calculation of `settle tx` and `close tx`.

**Review by omerfirmak — APPROVED** [review]

**Comment by omerfirmak** [comment]
a great read on the topic @linked0 
https://yakshaver.org/2021/07/26/first.html
