### PR TITLE
Fix #2363: Unify / clear up the REST API

### LINKED ISSUE #2363: Unify / clear up the REST API
Currently, we have multiple conventions used in the REST API, and most of them have problem, e.g.:
- `putTransaction`: Usage of `PUT` is wrong here, as a `PUT` should send a specific resource. But we just "submit" a transaction, so we should use `POST`. Something like `PUT /transaction/${TXID}` would be correct though. [More info](https://stackoverflow.com/questions/630453/what-is-the-difference-between-post-and-put-in-http#:~:text=POST%20means%20%22create%20new%22%20as,the%20server%20to%20create%20it.).
- `getEnrollment`: This gets the pending enrollments, not the externalized ones. I don't know if we want to provide an API to provide a specific enrollment that has already be externalized, but I think it might be confusing that this only returns enrollments in the pool;
- There is no way to get all pending enrollments (similar to https://github.com/bosagora/agora/issues/1481);
- `receivePreimage` is `POST reveice_preimage` => Should be `POST /preimage` or even `PUT /preimage/${UTXO_ID}`;
- `getTransactions` => Like `getEnrollment`, should indicate that they are pending txs. Also, #1481

There are probably other issues there, so the cleanup should be done by someone familiar with REST.
For anyone not familiar, [this is pretty great](https://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm).

### PR DESCRIPTION
**Pull request by Geod24**
The bulk of it has been done in #2428 , and the only point not addressed from the issue is its own issue.

### CODE REVIEW

**Review by linked0 — APPROVED** [review]
Neat!

File: source/agora/node/FullNode.d [hunk 1]
```diff
@@ -1057,13 +1057,27 @@ public class FullNode : API
...
-        return this.enroll_man.getValidatorPreimages(Height(start_height),
-            Height(end_height)).array();
+        this.recordReq("preimages_range");
+
+        const known = this.ledger.getBlockHeight();
+        // We have no data that could match this query
+        if (known < start_height)
+            return null;
+
+        // Bounds check end_height and make the API prractical
```
Comment (kchulj) [inline source/agora/node/FullNode.d:1072]:
```suggestion
        // Bounds check end_height and make the API practical
```

**Review by kchulj — APPROVED** [review]
LGTM one typo
