### PR TITLE
Check the result of `Ledger.prepareNominatingSet`

### LINKED ISSUE #900: Avoid nominating and externalizing Enrollments that will fail Block validation
There were several issues with nomination discovered in #899:
- [x] There were leftover `Enrollment` in the `EnrollmentPool` which were picked up to be nominated, although they were also in the `ValidatorSet`;
- [x] There is no check that the result of `Ledger.prepareNominatingSet` can in fact be nominated;
- [x] Other node achieved consensus on duplicated Enrollments (!)

All of this needs to be fixed. #899 was just a stopgap measure but nominating enrollment (and nomination in general) needs to be much more thought out.

### PR DESCRIPTION
**Pull request by linked0**
This checks the validity of a `ConsensusData` before nominating it. It should never happen, so we make this a `log.fatal` call.

Fixes #900

### CODE REVIEW

File: source/agora/consensus/protocol/Nominator.d [hunk 1]
```diff
@@ -179,6 +179,13 @@ extern(D):
         if (data.tx_set.length == 0)
             return;  // not ready yet
 
+        // check whether the consensus data is valid before nominating it.
+        if (auto msg = this.ledger.validateConsensusData(data))
+        {
+            log.fatal("tryNominate(): Invalid consensus data: {}", msg);
```
Comment (AndrejMitrovic) [inline source/agora/consensus/protocol/Nominator.d]: It's not fatal if the node continues running. Fatal means the node will shut down.

Comment (AndrejMitrovic) [reply source/agora/consensus/protocol/Nominator.d]: Ok it looks like @Geod24 wants this to be more than `log.error`, but we don't have `log.critical` for this purpose. So `log.fatal` is the next best thing, despite its name.

Keep this changeset.

Comment (AndrejMitrovic) [reply source/agora/consensus/protocol/Nominator.d]: Do we want to log out the actual consensus data too and not just the message?

Comment (linked0) [reply source/agora/consensus/protocol/Nominator.d]: > Do we want to log out the actual consensus data too and not just the message?

Logging out the data would be good.

**Comment by Geod24** [comment]
Can you rebase ?

**Review by Geod24 — APPROVED** [review]
Merge at will

File: source/agora/consensus/protocol/Nominator.d [hunk 2]
```diff
@@ -179,6 +179,14 @@ extern(D):
         if (data.tx_set.length == 0)
             return;  // not ready yet
 
+        // check whether the consensus data is valid before nominating it.
+        if (auto msg = this.ledger.validateConsensusData(data))
```
Comment (AndrejMitrovic) [inline source/agora/consensus/protocol/Nominator.d:183]: ~Although I question why this check is in here rather than inside of `prepareNominatingSet`. It seems like leaky abstractions?~

Question answered on slack.
